#!/usr/bin/env tsx
/**
 * Check Kernel Convergence Rate
 *
 * This script:
 * 1. Calculates Convergence Rate from KernelRegistry
 * 2. Creates GitHub Issue if rate < 70%
 * 3. Outputs JSON results
 *
 * Usage:
 *   npm run check-convergence
 *   tsx scripts/check-kernel-convergence.ts
 */

import { Octokit } from '@octokit/rest';
import { KernelRegistryService } from '../src/ssot/kernel-registry';
import { env } from '../src/config/env';

const CONVERGENCE_THRESHOLD = 70; // %

interface ConvergenceCheckResult {
  convergenceRate: number;
  threshold: number;
  isHealthy: boolean;
  totalKernels: number;
  agreedOrFrozenKernels: number;
  convergedKernels: number;
  timestamp: string;
  issueCreated: boolean;
  issueNumber?: number;
}

async function main() {
  console.log('🔍 Checking Kernel Convergence Rate...\n');

  // Initialize services
  const kernelRegistry = new KernelRegistryService();
  await kernelRegistry.load();

  // Calculate convergence rate
  const convergenceRate = await kernelRegistry.getConvergenceRate();
  const isHealthy = convergenceRate >= CONVERGENCE_THRESHOLD;

  // Get kernel statistics
  const allKernels = await kernelRegistry.getAllKernels();
  const agreedOrFrozen = allKernels.filter(
    (k) => k.maturity === 'agreed' || k.maturity === 'frozen'
  );

  let convergedKernels = 0;
  for (const kernel of agreedOrFrozen) {
    const validation = await kernelRegistry.validateNRVV(kernel.id);
    if (validation.isValid && validation.traceabilityComplete) {
      convergedKernels++;
    }
  }

  const result: ConvergenceCheckResult = {
    convergenceRate: parseFloat(convergenceRate.toFixed(2)),
    threshold: CONVERGENCE_THRESHOLD,
    isHealthy,
    totalKernels: allKernels.length,
    agreedOrFrozenKernels: agreedOrFrozen.length,
    convergedKernels,
    timestamp: new Date().toISOString(),
    issueCreated: false,
  };

  console.log(`📊 Convergence Rate: ${result.convergenceRate}%`);
  console.log(`📈 Threshold: ${result.threshold}%`);
  console.log(`📦 Total Kernels: ${result.totalKernels}`);
  console.log(`✅ Agreed/Frozen: ${result.agreedOrFrozenKernels}`);
  console.log(`🎯 Converged: ${result.convergedKernels}\n`);

  // Create Issue if convergence rate is below threshold
  if (!isHealthy && env.githubToken && env.githubRepository) {
    console.log('⚠️  Convergence rate below threshold, creating Issue...\n');

    try {
      const octokit = new Octokit({ auth: env.githubToken });
      const [owner, repo] = env.githubRepository.split('/');

      // Find incomplete kernels
      const incompleteKernels: Array<{
        id: string;
        statement: string;
        missingItems: string[];
      }> = [];

      for (const kernel of agreedOrFrozen) {
        const validation = await kernelRegistry.validateNRVV(kernel.id);
        if (!validation.isValid || !validation.traceabilityComplete) {
          const missingItems: string[] = [];
          if (validation.needsCount === 0) missingItems.push('Needs');
          if (validation.requirementsCount === 0) missingItems.push('Requirements');
          if (validation.verificationCount === 0) missingItems.push('Verification');
          if (validation.validationCount === 0) missingItems.push('Validation');
          if (!validation.traceabilityComplete) missingItems.push('Traceability');

          incompleteKernels.push({
            id: kernel.id,
            statement: kernel.statement,
            missingItems,
          });
        }
      }

      // Build Issue body
      const issueBody = `## ⚠️ Kernel Convergence Rate Alert

**Current Convergence Rate**: ${result.convergenceRate}%
**Threshold**: ${result.threshold}%
**Status**: 🔴 Below Threshold

### Summary

- **Total Kernels**: ${result.totalKernels}
- **Agreed/Frozen Kernels**: ${result.agreedOrFrozenKernels}
- **Fully Converged Kernels**: ${result.convergedKernels}
- **Incomplete Kernels**: ${incompleteKernels.length}

### Incomplete Kernels

${
  incompleteKernels.length > 0
    ? incompleteKernels
        .map(
          (k) =>
            `- **${k.id}**: ${k.statement}\n  - Missing: ${k.missingItems.join(', ')}`
        )
        .join('\n')
    : '*No incomplete kernels found*'
}

### Recommended Actions

1. Review incomplete Kernels and add missing NRVV items
2. Ensure all Requirements have proper traceability links
3. Add Verification and Validation patterns where missing
4. Update Kernel maturity to \`agreed\` or \`frozen\` once complete

### Automation

This Issue was automatically created by the weekly Kernel Convergence monitoring workflow.

**Timestamp**: ${result.timestamp}

---

*Generated by Luna's Self-Improvement Loop*`;

      const issueResponse = await octokit.issues.create({
        owner,
        repo,
        title: `[AUTO] Kernel Convergence Rate below ${CONVERGENCE_THRESHOLD}% (${result.convergenceRate}%)`,
        body: issueBody,
        labels: [
          '📊 priority:P1-High',
          '⚠️ type:maintenance',
          '🤖 agent:coordinator',
          '📥 state:pending',
        ],
      });

      result.issueCreated = true;
      result.issueNumber = issueResponse.data.number;

      console.log(`✅ Issue #${result.issueNumber} created successfully`);
      console.log(`   ${issueResponse.data.html_url}\n`);
    } catch (error) {
      console.error('❌ Failed to create Issue:', (error as Error).message);
    }
  } else if (!isHealthy) {
    console.log('⚠️  Convergence rate below threshold');
    console.log('   (GitHub token not configured, skipping Issue creation)\n');
  } else {
    console.log('✅ Convergence rate healthy!\n');
  }

  // Output JSON result
  console.log('📄 JSON Output:');
  console.log(JSON.stringify(result, null, 2));

  // Exit with non-zero code if unhealthy
  if (!isHealthy) {
    process.exit(1);
  }
}

main().catch((error) => {
  console.error('❌ Error:', error);
  process.exit(1);
});
